
# Each key of the below dictionary represents the id of a SWIM related user whose credentials will be saved in a file
for further use
# <USER_ID>_USER=<provided_username>
# <USER_ID>_PASS=<provided_password>

USERS:
  DB: swim
  SM_ADMIN: swim-sm-admin
  SWIM_ADSB: swim-adsb
  SWIM_EXPLORER: swim-explorer
