
# Each key of the below dictionary represents the id of a SWIM related user whose credentials will be saved in a file
# for further use
# <USER_ID>_USER=<provided_username>
# <USER_ID>_PASS=<provided_password>

USERS:
  DB:
    description: Database user
    default_user: swim
  SM_ADMIN:
    description: Subscription Manager admin user
    default_user: swim-sm-admin
  SWIM_ADSB:
    description: SWIM ADSB user for Subscription Manager
    default_user: swim-adsb
  SWIM_EXPLORER:
    description: SWIM Explorer user for Subscription Manager
    default_user: swim-explorer
