
# Each key of the below dictionary represents the id of a SWIM related user whose credentials will be saved in
# every file (.env) of its provided file list in the following format:
# <USER_ID>_USERNAME=<provided_username>
# <USER_ID>_PASSWORD=<provided_password>

ENV_FILE_PATHS_PER_USER:
  DB:
    - "/tmp/db.env"
  SM_ADMIN:
    - "/tmp/sm_admin.env"
  SWIM_ADSB:
    - "/tmp/swim_adsb.env"
  SWIM_EXPLORER:
    - "/tmp/swim_explorer.env"
